// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjzhntrcogbamirtudsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqemhudHJjb2diYW1pcnR1ZHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDM1NzAsImV4cCI6MjA4MzkxOTU3MH0.e_cG4R49Je7Cs5420vyEoi05c4Jy29lmnP2ZYbKaSmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});